spring:
  profiles:
    active: console, database, actuator, service
  application:
      name: api-call

server:
  port: ${SERVER_PORT:8000}
  address: ${SERVER_ADDRESS:localhost}
  ssl:
    enabled: ${SSL_CHECK:false}
  servlet:
    context-path: /api